apiVersion: v1
kind: Namespace
metadata:
  name: odin-catalog
  labels:
    app.kubernetes.io/part-of: odin-catalog
    # Required for OpenSearch privileged init container (sysctl vm.max_map_count)
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
